apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  Caddyfile: |
{{ .Values.caddyfile | nindent 4 }}
